#!/usr/bin/env bash
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
#In a list format
for number in {1..100}
do
    if [ $((number%3)) -eq 0 ] && [ $((number%5)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((number%3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((number%5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$number"
    fi
done
