#!/usr/bin/env bash
#loop 10 iterations and three especific conditionals
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
x="0"
while [ $x -lt 10 ]
do
    if [ $x -eq 4 ]
    then
        echo "Bad Luck"
    elif [ $x -eq 8 ]
    then
        echo "Good Luck"
    else
        echo "Best School"
    fi
    x=$((x+1))
done
