#!/usr/bin/env bash
#loop 10 iterations and three especific conditionals
i="0"
while [ $i -lt 10 ]
do
	if ((i == 3))
	then
		echo "bad luck"
	elif ((i == 7))
	then 
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
