#!/usr/bin/env bash
#script that displays numbers from 1 to 20
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration
x=1
while [ $x -le 21 ]
do
    echo "$x"
    case $x in
        4)
            echo "Bad Luck from China"
            ;;
        9)
            echo "Bad Luck from Japan"
            ;;
        17)
            echo "Bad Luck from Italy"
            ;;
    esac
    x=$((x+1))
done
